const POSTS = {
  LOAD: 'REQUEST_POSTS_START',
  LOAD_SUCCESS: 'RECEIVE_POSTS',
  LOAD_FAILED: 'LOAD_FAILED',
}

const POST_DETAILS = {
  LOAD: 'REQUEST_POST_START',
  LOAD_SUCCESS: 'SINGLE_POST_SUCCESS',
  LOAD_FAILED: 'SINGLE_POST_FAILED',
}

const POST_DELETE = {
  LOAD: 'DELETE_POSTS_START',
  DELETE_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_FAILED: 'DELETE_POST_FAILED',
}

const POST_UPDATE = {
  LOAD: 'UPDATE_POST_START',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_FAILED: 'UPDATE_POST_FAILED',
}

const POST_SEARCH = {
  LOAD: 'SEARCH_POST_START',
  SEARCH_POST_SUCCESS: 'SEARCH_POST_SUCCESS',
  SEARCH_POST_FAILED: 'SEARCH_POST_FAILED',
}
export default { POSTS, POST_DETAILS, POST_DELETE, POST_UPDATE, POST_SEARCH }
